import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header/page'
import { Nunito } from 'next/font/google'
import { UserProvider } from '../../context/UserContext'
import { Provider } from 'react-redux'
import store from '../../store'

const inter = Inter({ subsets: ['latin'] })

const font = Nunito({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
    <UserProvider >
    <html lang="en">
      <body className={font.className}>
        <Header/>
        {children}</body>
    </html>
     </UserProvider>
     </Provider>
  )
}
